// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/login": {
    params: {};
  };
  "/invite/:token": {
    params: {
      "token": string;
    };
  };
  "/dashboard": {
    params: {};
  };
  "/upload": {
    params: {};
  };
  "/calendar": {
    params: {};
  };
  "/reports": {
    params: {};
  };
  "/rate-card": {
    params: {};
  };
  "/team": {
    params: {};
  };
  "/settings": {
    params: {};
  };
  "/news": {
    params: {};
  };
  "/help": {
    params: {};
  };
  "/analytics": {
    params: {};
  };
  "/analytics/overtime": {
    params: {};
  };
  "/analytics/cap": {
    params: {};
  };
  "/analytics/payroll-review": {
    params: {};
  };
  "/analytics/payroll-revenue": {
    params: {};
  };
  "/validation": {
    params: {};
  };
  "/validation/timecard": {
    params: {};
  };
  "/validation/routes": {
    params: {};
  };
  "/validation/routes/invoice": {
    params: {};
  };
  "/validation/fleet/rfs-afs": {
    params: {};
  };
  "/validation/fleet/revenue": {
    params: {};
  };
  "/validation/fleet/rental": {
    params: {};
  };
  "/validation/fleet/repair": {
    params: {};
  };
  "/validation/fleet/insurance": {
    params: {};
  };
  "/*": {
    params: {
      "*": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/login" | "/invite/:token" | "/dashboard" | "/upload" | "/calendar" | "/reports" | "/rate-card" | "/team" | "/settings" | "/news" | "/help" | "/analytics" | "/analytics/overtime" | "/analytics/cap" | "/analytics/payroll-review" | "/analytics/payroll-revenue" | "/validation" | "/validation/timecard" | "/validation/routes" | "/validation/routes/invoice" | "/validation/fleet/rfs-afs" | "/validation/fleet/revenue" | "/validation/fleet/rental" | "/validation/fleet/repair" | "/validation/fleet/insurance" | "/*";
  };
  "routes/login.tsx": {
    id: "routes/login";
    page: "/login";
  };
  "routes/invite.tsx": {
    id: "routes/invite";
    page: "/invite/:token";
  };
  "routes/_protected.tsx": {
    id: "routes/_protected";
    page: "/" | "/dashboard" | "/upload" | "/calendar" | "/reports" | "/rate-card" | "/team" | "/settings" | "/news" | "/help" | "/analytics" | "/analytics/overtime" | "/analytics/cap" | "/analytics/payroll-review" | "/analytics/payroll-revenue" | "/validation" | "/validation/timecard" | "/validation/routes" | "/validation/routes/invoice" | "/validation/fleet/rfs-afs" | "/validation/fleet/revenue" | "/validation/fleet/rental" | "/validation/fleet/repair" | "/validation/fleet/insurance";
  };
  "routes/index.tsx": {
    id: "routes/index";
    page: "/";
  };
  "routes/dashboard.tsx": {
    id: "routes/dashboard";
    page: "/dashboard";
  };
  "routes/upload.tsx": {
    id: "routes/upload";
    page: "/upload";
  };
  "routes/calendar.tsx": {
    id: "routes/calendar";
    page: "/calendar";
  };
  "routes/reports.tsx": {
    id: "routes/reports";
    page: "/reports";
  };
  "routes/rate-card.tsx": {
    id: "routes/rate-card";
    page: "/rate-card";
  };
  "routes/team.tsx": {
    id: "routes/team";
    page: "/team";
  };
  "routes/settings.tsx": {
    id: "routes/settings";
    page: "/settings";
  };
  "routes/news.tsx": {
    id: "routes/news";
    page: "/news";
  };
  "routes/help.tsx": {
    id: "routes/help";
    page: "/help";
  };
  "routes/analytics/index.tsx": {
    id: "routes/analytics/index";
    page: "/analytics";
  };
  "routes/analytics/overtime.tsx": {
    id: "routes/analytics/overtime";
    page: "/analytics/overtime";
  };
  "routes/analytics/cap.tsx": {
    id: "routes/analytics/cap";
    page: "/analytics/cap";
  };
  "routes/analytics/payroll-review.tsx": {
    id: "routes/analytics/payroll-review";
    page: "/analytics/payroll-review";
  };
  "routes/analytics/payroll-revenue.tsx": {
    id: "routes/analytics/payroll-revenue";
    page: "/analytics/payroll-revenue";
  };
  "routes/validation/index.tsx": {
    id: "routes/validation/index";
    page: "/validation";
  };
  "routes/validation/timecard.tsx": {
    id: "routes/validation/timecard";
    page: "/validation/timecard";
  };
  "routes/validation/routes/index.tsx": {
    id: "routes/validation/routes/index";
    page: "/validation/routes";
  };
  "routes/validation/routes/invoice.tsx": {
    id: "routes/validation/routes/invoice";
    page: "/validation/routes/invoice";
  };
  "routes/validation/fleet/rfs-afs.tsx": {
    id: "routes/validation/fleet/rfs-afs";
    page: "/validation/fleet/rfs-afs";
  };
  "routes/validation/fleet/revenue.tsx": {
    id: "routes/validation/fleet/revenue";
    page: "/validation/fleet/revenue";
  };
  "routes/validation/fleet/rental.tsx": {
    id: "routes/validation/fleet/rental";
    page: "/validation/fleet/rental";
  };
  "routes/validation/fleet/repair.tsx": {
    id: "routes/validation/fleet/repair";
    page: "/validation/fleet/repair";
  };
  "routes/validation/fleet/insurance.tsx": {
    id: "routes/validation/fleet/insurance";
    page: "/validation/fleet/insurance";
  };
  "routes/not-found.tsx": {
    id: "routes/not-found";
    page: "/*";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/login": typeof import("./app/routes/login.tsx");
  "routes/invite": typeof import("./app/routes/invite.tsx");
  "routes/_protected": typeof import("./app/routes/_protected.tsx");
  "routes/index": typeof import("./app/routes/index.tsx");
  "routes/dashboard": typeof import("./app/routes/dashboard.tsx");
  "routes/upload": typeof import("./app/routes/upload.tsx");
  "routes/calendar": typeof import("./app/routes/calendar.tsx");
  "routes/reports": typeof import("./app/routes/reports.tsx");
  "routes/rate-card": typeof import("./app/routes/rate-card.tsx");
  "routes/team": typeof import("./app/routes/team.tsx");
  "routes/settings": typeof import("./app/routes/settings.tsx");
  "routes/news": typeof import("./app/routes/news.tsx");
  "routes/help": typeof import("./app/routes/help.tsx");
  "routes/analytics/index": typeof import("./app/routes/analytics/index.tsx");
  "routes/analytics/overtime": typeof import("./app/routes/analytics/overtime.tsx");
  "routes/analytics/cap": typeof import("./app/routes/analytics/cap.tsx");
  "routes/analytics/payroll-review": typeof import("./app/routes/analytics/payroll-review.tsx");
  "routes/analytics/payroll-revenue": typeof import("./app/routes/analytics/payroll-revenue.tsx");
  "routes/validation/index": typeof import("./app/routes/validation/index.tsx");
  "routes/validation/timecard": typeof import("./app/routes/validation/timecard.tsx");
  "routes/validation/routes/index": typeof import("./app/routes/validation/routes/index.tsx");
  "routes/validation/routes/invoice": typeof import("./app/routes/validation/routes/invoice.tsx");
  "routes/validation/fleet/rfs-afs": typeof import("./app/routes/validation/fleet/rfs-afs.tsx");
  "routes/validation/fleet/revenue": typeof import("./app/routes/validation/fleet/revenue.tsx");
  "routes/validation/fleet/rental": typeof import("./app/routes/validation/fleet/rental.tsx");
  "routes/validation/fleet/repair": typeof import("./app/routes/validation/fleet/repair.tsx");
  "routes/validation/fleet/insurance": typeof import("./app/routes/validation/fleet/insurance.tsx");
  "routes/not-found": typeof import("./app/routes/not-found.tsx");
};